import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
	id 'com.android.application'
	id 'kotlin-android'
	id 'com.google.devtools.ksp'
	id 'kotlin-parcelize'
	id 'dagger.hilt.android.plugin'
	id 'androidx.room'
	id 'org.jetbrains.kotlin.plugin.serialization'
}

android {
	compileSdkVersion 'android-37.0'
	buildToolsVersion = '37.0.0'
	namespace = 'org.draken.usagi'

	defaultConfig {
		applicationId 'org.draken.usagi'
		minSdk = 21
		targetSdk = 37
		versionCode = 19
		versionName = '1.0.0-rc2'
		generatedDensities = []
		testInstrumentationRunner 'org.draken.usagi.HiltTestRunner'
		ksp {
			arg('room.generateKotlin', 'true')
		}
		androidResources {
			// https://issuetracker.google.com/issues/408030127
			generateLocaleConfig false
		}
	}
	dependenciesInfo {
		includeInApk = false
		includeInBundle = false
	}
	signingConfigs {
		release {
			def keystorePropertiesFile = rootProject.file('keystore.properties')
			if (keystorePropertiesFile.exists()) {
				def keystoreProperties = new Properties()
				keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
				storeFile file(keystoreProperties['storeFile'])
				storePassword keystoreProperties['storePassword']
				keyAlias keystoreProperties['keyAlias']
				keyPassword keystoreProperties['keyPassword']
			}
		}
	}
	buildTypes {
		debug {
			applicationIdSuffix = '.debug'
		}
		release {
			minifyEnabled true
			shrinkResources true
			proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
			signingConfig signingConfigs.release
		}
	}
	buildFeatures {
		viewBinding true
		buildConfig true
	}
	packagingOptions {
		resources {
			excludes += [
				'META-INF/README.md',
				'META-INF/NOTICE.md',
				'META-INF/LICENSE',
				'META-INF/LICENSE.md',
				'META-INF/DEPENDENCIES',
				'META-INF/*.kotlin_module',
				'META-INF/*.version',
				'DebugProbesKt.bin',
				'kotlin-tooling-metadata.json',
				'**/*.kotlin_builtins',
				'META-INF/ASL2.0',
				'META-INF/AL2.0',
				'META-INF/LGPL2.1',
				'META-INF/proguard/**',
				'META-INF/compiler_release',
				'META-INF/**/*.txt',
				'META-INF/**/*.md',
				'**/*.kotlin_metadata',
				'**/*.kotlin_module',
				'**/*.proto',
				'META-INF/services/javax.annotation.processing.Processor'
			]
		}
	}
	sourceSets {
		androidTest.assets.srcDirs += files("$projectDir/schemas".toString())
		main.java.srcDirs += 'src/main/kotlin/'
	}
	compileOptions {
		coreLibraryDesugaringEnabled true
		sourceCompatibility JavaVersion.VERSION_17
		targetCompatibility JavaVersion.VERSION_17
	}
    kotlin {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
            freeCompilerArgs.addAll(
                "-opt-in=kotlin.ExperimentalStdlibApi",
                "-opt-in=kotlinx.coroutines.ExperimentalCoroutinesApi",
                "-opt-in=kotlinx.coroutines.ExperimentalForInheritanceCoroutinesApi",
                "-opt-in=kotlinx.coroutines.InternalForInheritanceCoroutinesApi",
                "-opt-in=kotlinx.coroutines.FlowPreview",
                "-opt-in=kotlin.contracts.ExperimentalContracts",
                "-opt-in=coil3.annotation.ExperimentalCoilApi",
                "-opt-in=coil3.annotation.InternalCoilApi",
                "-opt-in=kotlinx.serialization.ExperimentalSerializationApi",
                "-Xjspecify-annotations=strict",
                "-Xannotation-default-target=first-only",
                "-Xcontext-parameters",
                "-Xtype-enhancement-improvements-strict-mode",
                "-Xno-param-assertions",
                "-Xno-call-assertions",
                "-Xno-receiver-assertions"
            )
        }
    }
	room {
		schemaDirectory "$projectDir/schemas"
	}
	lint {
		abortOnError true
		disable 'MissingTranslation', 'PrivateResource', 'SetJavaScriptEnabled', 'SimpleDateFormat'
	}
	testOptions {
		unitTests.includeAndroidResources true
		unitTests.returnDefaultValues false
		kotlin {
            compilerOptions {
                freeCompilerArgs.add(
                    "-opt-in=tsuki.InternalParsersApi"
                )
            }
		}
	}
}
dependencies {
	implementation libs.usagi.serialization.library
	ksp libs.usagi.serialization.library
	implementation libs.jsoup
	implementation libs.tsuki
	implementation libs.tsukimix
	coreLibraryDesugaring libs.desugar.jdk.libs
	implementation libs.kotlin.stdlib
	implementation libs.kotlinx.coroutines.android
	implementation libs.kotlinx.coroutines.guava

	implementation libs.androidx.appcompat
	implementation libs.androidx.core
	implementation libs.androidx.activity
	implementation libs.androidx.fragment
	implementation libs.androidx.transition
	implementation libs.androidx.collection
	implementation libs.lifecycle.viewmodel
	implementation libs.lifecycle.service
	implementation libs.lifecycle.process
	implementation libs.androidx.constraintlayout
	implementation libs.androidx.documentfile
	implementation libs.androidx.swiperefreshlayout
	implementation libs.androidx.recyclerview
	implementation libs.androidx.viewpager2
	implementation libs.androidx.preference
	implementation libs.androidx.biometric
	implementation libs.material
	implementation libs.androidx.lifecycle.common.java8
	implementation libs.androidx.webkit

	implementation libs.androidx.work.runtime
	implementation libs.guava

    // Foldable/Window layout
    implementation libs.androidx.window

	implementation libs.androidx.room.runtime
	implementation libs.androidx.room.ktx
	ksp libs.androidx.room.compiler

	implementation libs.okhttp
	implementation libs.okhttp.tls
	implementation libs.okhttp.dnsoverhttps
	implementation libs.okio
	implementation libs.rxjava
	implementation libs.injekt.core
	implementation libs.kotlinx.serialization.core
	implementation libs.kotlinx.serialization.json
	implementation libs.kotlinx.serialization.json.okio

	implementation libs.adapterdelegates
	implementation libs.adapterdelegates.viewbinding

	implementation libs.hilt.android
	ksp libs.hilt.compiler
	implementation libs.androidx.hilt.work
	ksp libs.androidx.hilt.compiler

	implementation libs.coil.core
	implementation libs.coil.network
	implementation libs.coil.gif
	implementation libs.coil.svg
	implementation libs.avif.decoder
	implementation libs.ssiv
	implementation libs.disk.lru.cache
	implementation libs.markwon
	implementation(libs.usagi.rpc) {
		exclude group: 'org.json', module: 'json'
	}

	implementation libs.conscrypt.android

	debugImplementation libs.leakcanary.android
	debugImplementation libs.workinspector

	testImplementation libs.junit
	testImplementation libs.json
	testImplementation libs.kotlinx.coroutines.test

	androidTestImplementation libs.androidx.runner
	androidTestImplementation libs.androidx.rules
	androidTestImplementation libs.androidx.test.core
	androidTestImplementation libs.androidx.junit

	androidTestImplementation libs.kotlinx.coroutines.test

	androidTestImplementation libs.androidx.room.testing
	androidTestImplementation libs.moshi.kotlin

	androidTestImplementation libs.hilt.android.testing
	kspAndroidTest libs.hilt.android.compiler
}
